server:
  port: 9000
spring:
  application:
    name: recruit
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_recruit?characterEncoding=utf-8

  jpa:
    database: mysql
    show-sql: true